#!/bin/bash

# Colors
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`



echo "#------------------------------------------------#"
echo "#	*${green}STARTING INSTALLATION${reset}*"
echo "#------------------------------------------------#"
echo ""

# Install zsh
echo "#------------------------------------------------#"
echo "#	*${green}OH-MY-ZSH${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""

[ -f $HOME/.oh-my-zsh ] && rm -rf $HOME/.oh-my-zsh
curl -L http://install.ohmyz.sh | sh

# Global gitigore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
[ -f $HOME/.zshrc ] && rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc


# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc


rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
#cd ~/.oh-my-zsh/themes/
#git checkout d6a36b1 agnoster.zsh-theme

# Install composer
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}COMPOSER${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
cd ~/.dotfiles
curl -sS https://getcomposer.org/installer | php
mv -f composer.phar /usr/local/bin/composer

# Install homebrew
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}HOMEBREW${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install wget
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}WGET${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
brew install wget --overwrite

# Install httpie disk analyzer
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}HTTPIE${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
brew install httpie

# Install ncdu
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}NCDU${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
brew install ncdu

# Install envoy
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}LARAVEL ENVOY${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
composer global require "laravel/envoy=~1.0"

# Install PHP CS Fixer
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}PHP CS FIXER${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
composer global require friendsofphp/php-cs-fixer

# Install Laravel Installer
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}Laravel installer${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
composer global require "laravel/installer"

# Install php 7.0
# Using http://php-osx.liip.ch/
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}PHP 7.1${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php71
brew install php71-xdebug
sudo brew services start homebrew/php/php71
brew install homebrew/php/php71-mcrypt
brew install homebrew/php/php71-imagick

# Install Redis
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}Redis${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
brew install redis
brew install --HEAD homebrew/php/php71-redis

# Install Laravel Valet
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}Laravel Valet${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
composer global require laravel/valet
valet install

# Install MariaDB
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}MariaDB${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
brew install mariadb

# Install Yarn
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}Yarn${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
brew install yarn

# Install Gulp
echo ""
echo "#------------------------------------------------#"
echo "#	*${green}Gulp${reset}* Installing..."
echo "#------------------------------------------------#"
echo ""
npm install -g gulp


echo ""
echo "#------------------------------------------------#"
echo "#	*${green}FINISHED INSTALLATION${reset}*"
echo "#------------------------------------------------#"
echo ""

echo "#------------------------------------------------#"
echo "#	*${green}NEXT${reset}* Next steps"
echo "#------------------------------------------------#"
echo ""

# Patch font contains right characters for promt
echo "1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf" 

# Install solarized http://ethanschoonover.com/solarized
echo "2. Install patched solarized theme included in ~/.dotfiles/misc"
echo ""

echo "#------------------------------------------------#"
echo "#	*${green}OPTIONAL${reset}*"
echo "#------------------------------------------------#"
echo ""

echo "1. Set some sensible os x defaults by running: $HOME/.dotfiles/osx/set-defaults.sh"

echo ""
echo "#------------------------------------------------#"
echo "#	*${green}THE END${reset}*"
echo "#------------------------------------------------#"

# Reload shell settings
. ~/.zshrc
